### ISSUE TITLE
delq crashes if the user has too many quotes

### ISSUE THREAD

**Issue by Adoria** [Adoria/Martlet#25]
Caused by the embed generated by the bot being too large to be sent in a single message.
Potential fixes: Provide navigable "pages" of quotes and/or truncate each quote to X characters

**Comment by jidicula** [comment]
don't make stupid-long quotes then

**Comment by Adoria** [comment]
While that is another potential fix, I'd like to keep my pasta as fresh as possible.

**Comment by jidicula** [comment]
Fixed in #44 by @lamminade !
