### ISSUE TITLE
wttr caches old forecasts

### ISSUE THREAD

**Issue by jidicula** [Adoria/Martlet#30]
See [here](https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vd3R0ci5pbi9Nb250cmVhbF8ybXBxX2xhbmc9ZW4ucG5nIn0.PGKXxg-z0DJxY7A02Sf_x9nwizY?width=400&height=190). This is from a query today, but the forecast is from yesterday.

**Comment by Adoria** [comment]
Fixed in 544bdc876b69fadd28878a173145b1154dd86e45.
